# 0. Introduction

#### Credit
Much of the material of this workshop is created by the author (George Datseris). A significant part though comes from other sources:

* The JuliaBox tutorials for the core language
* Exercises from exercism.io
* Exercises from http://ucidatascienceinitiative.github.io/IntroToJulia/
* Talk of Stefan Karpinski, "The Unreasonable Effectiveness of Multiple Dispatch"



## 0.1. What is Julia?

[Julia](https://julialang.org/) is a relatively new programming language, developed at MIT, with version 1.0 released in August 2018. Even though it is so recent, it has taken the scientific community by storm and many serious large scale projects have started in Julia. For example, see CliMA.

The following **facts** about Julia justify why so many scientists are willing to learn a new language:

- Performance as good as C/Fortran
- Dynamic, interactive language
- Intuitive, expressive and high-level syntax
- General purpose as well as HPC
- Multiple dispatch
- Interoperability and "free" extension-ability of all Julia packages
- Natively able to call C, Fortran, Python, etc...
- Free and open source
- Thriving ecosystem

Because these are **facts**, I won't be wasting effort confirming them in this tutorial.

## 0.2. Why should I learn Julia?

*(in the author's personal opinion)*

- It solves the two language problem: allows interactive exploration of your system with highest performance.
- It offers a syntax that is intuitive and easy to read. Your own code does not differ much from Julia's base code.
- Unicode makes math expressions in code feel natural.
- Multiple dispatch and functional programming are most suitable to implement scientific thought in code.
- Its so darn easy to extend other's people code and then for other people to extend your code!
- A lot of code re-use leads to rapid development and more features than would be possible with other languages.

Specifically for the authors of this conference:

- The [JuliaDynamics](https://juliadynamics.github.io/JuliaDynamics/) organization.

# 1. Basic Julia

## 1.1 Basic syntax and unicode

- Assingment in Julia is done with the `=` sign. 
- You can assign *anything* to a variable binding.
- The variable names can include pretty much any Unicode character.
- Strings are created between double quotes `"` while the single quotes `'` are used for characters only.
- Most Julia editors offer "LaTeX Completion". Pressing e.g. `\delta` and then TAB will create the corresponding Unicode character using the LaTeX syntax.
- **All Julia operations return a value**. This includes assingment.
- Everything that exists in Julia has a certain **Type**. (e.g. numbers can be integers, floats, rationals. This will be important later on)

Here are some examples:

In [1]:
x = 3

3

In [2]:
y = x ^ 2.5 # powers with ^

15.588457268119896

In [3]:
δ = "αbasf"

"αbasf"

In [4]:
😺, 😀, 😞 = 1, 0, -1

(1, 0, -1)

In [5]:
😺 + 😞 == 😀

true

To find the type of a thing in Julia you simply use `typeof`:

In [6]:
typeof(😺)

Int64

In [7]:
typeof(1.5)

Float64

In [8]:
typeof("asdf")

String

Lastly, variables can be interpolated into strings using `$`, like so:

In [9]:
"the value of the cat face (😺) is $😺"

"the value of the cat face (😺) is 1"

## 1.2. Basic datastructures

Indexing in Julia is done with brackets: `thing[index]`. The `index` depends on the datastructure you have.

### Tuples
Tuples are ordered immutable collections of elements. They are mostly used when the elements are not of the same type with each other and are intended to be used for small collections.

Syntax:

```julia
(item1, item2, ...)```

In [10]:
myfavoritethings = ("penguins", "cats", π)

("penguins", "cats", π = 3.1415926535897...)

In [11]:
myfavoritethings[1]

"penguins"

In [12]:
typeof(myfavoritethings[3])

Irrational{:π}

### Dictionaries
Dictionaries are unordered mutable collections of pairs key-value. They are intended for sets of relational data, that is accessed via a key. Dictionaries have a specific type for keys and values.

Syntax:
```julia
Dict(key1 => value1, key2 => value2, ...)```

A good example of a dictionary is a contacts list, where we associate names with phone numbers.

In [13]:
myphonebook = Dict("Jenny" => "867-5309", "Ghostbusters" => "555-2368")

Dict{String,String} with 2 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => "555-2368"

In [14]:
myphonebook["Jenny"]

"867-5309"

New entries can be added to the above dictionary, because it is mutable. However, the key of the entry must be of type `String` and the value of the entry must be of type `String`.

In [15]:
myphonebook["BuzzLightyear"] = "∞ and beyond"

myphonebook # this displays the phonebook

Dict{String,String} with 3 entries:
  "Jenny"         => "867-5309"
  "BuzzLightyear" => "∞ and beyond"
  "Ghostbusters"  => "555-2368"

### NamedTuples

These are exactly like tuples but also assign a name to each variable they contain. They rest between the `Tuple` and `Dict` type in their use.

Their syntax is:
```julia
(key1 = val1, key2 = val2, ...)
```
For example:

In [16]:
nt = (x = 5, y = "str", z = 5//3)

(x = 5, y = "str", z = 5//3)

These objects can be accessed with `[]` like normal tuples, but also with the syntax `.key`:

In [17]:
nt[1] == nt.x

true

### Arrays

The standard Julia `Array` is a mutable and ordered collection of items of the same type.
The dimensionality of the Julia array is important. A `Matrix` is an array of dimension 2. A `Vector` is an array of dimension 1. The *element type* of an array contains is irrelevant to its dimension!

**i.e. a Vector of Vectors of Numbers and a Matrix of Numbers are two totally different things!**

Syntax: <br>
```julia
[item1, item2, ...]```


For example:

In [18]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]

5-element Array{String,1}:
 "Ted"     
 "Robyn"   
 "Barney"  
 "Lily"    
 "Marshall"

In [19]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [20]:
mixture = [1, 1, 2, 3, "Ted", "Robyn"]

6-element Array{Any,1}:
 1       
 1       
 2       
 3       
  "Ted"  
  "Robyn"

As mentioned, the type of the elements of an array must be the same. Yet above we mix numbers with strings! I wasn't lying though; the above array is an **unoptimized** version that can hold **any** thing. You can see this in the "type" of the array, whicn is to the left of its dimenmsionality: `Array{TypeOfTheThings, Dimensionality}`. For `mixture` it is `Any`.

Arrays of other data structures, e.g. vectors or dictionaries, or anything, as well as multi-dimensional arrays are possible:

In [21]:
vectors_of_numbers = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

3-element Array{Array{Int64,1},1}:
 [1, 2, 3]   
 [4, 5]      
 [6, 7, 8, 9]

In [22]:
R = rand(4, 3)

4×3 Array{Float64,2}:
 0.865506  0.932704  0.914875
 0.572916  0.297632  0.493417
 0.774574  0.866382  0.37947 
 0.447228  0.492262  0.892097

In [23]:
R[1,2] # two dimensional indexing

0.9327044020627211

Since arrays are mutable we can change their entries, or even add new ones:

In [24]:
fibonacci[1] = 15

15

In [25]:
push!(fibonacci, 16) # push! also returns fibonacci, hence it is displayed

8-element Array{Int64,1}:
 15
  1
  2
  3
  5
  8
 13
 16

## 1.3. Iteration
Iteration in Julia is high-level. This means that not only it has an intuitive and simple syntax, but also iteration works with anything that can be iterated. Iteration can also be extended (more on that later).


### `for` loops

The syntax for a `for` loop is

```julia
for *var* in *loop iterable*
    *loop body*
end
```

*you will notice that all Julia code-blocks end with `end`*

In [26]:
for n in 1:5
    println(n)
end

1
2
3
4
5


In [27]:
for (key, val) in myphonebook
    println("The number of $key is $val")
end

The number of Jenny is 867-5309
The number of BuzzLightyear is ∞ and beyond
The number of Ghostbusters is 555-2368


### `while` loops

The syntax for a standard `while` loop is

```julia
while *condition*
    *loop body*
end
```

In [28]:
n = 0
while n < 5
    n += 1
    println(n)
end

1
2
3
4
5



## 1.4. Conditionals

#### with `if`

In Julia, the syntax

```julia
if *condition 1*
    *option 1*
elseif *condition 2*
    *option 2*
else
    *option 3*
end
```

evaluates the conditions and executes the code-block of the first true condition.

In [29]:
x, y = 5, 6
if x > y
    x    # all Julia code blocks by default return the last executed expression
else
    y
end

6

#### with ternary operators

For this last block, we could instead use the ternary operator with the syntax

```julia
a ? b : c
```

which equates to 

```julia
if a
    b
else
    c
end
```

In [30]:
x > y ? x : y

6

Notice that both the boolean conditions, as well as the conditional code blocks, can be nested and chained to arbitrary degree. E.g. this is normal syntax:

```julia
(z < x && y > w) ? 13 : z < x/2 ? 14 : 15
```

## 1.5. Functions
Functions are the bread and butter of Julia, which heavily supports functional programming.
Functions are objects by themselves and can be used as any other Julia value.

Functions are declared with two ways:

In [31]:
function f(x)
    x^2      # all Julia code blocks by default return the last executed expression
end

f(x) = x^2  # equivalent with above

f (generic function with 1 method)

And called using their name and parenthesis `()` enclosing the calling arguments:

In [32]:
f(5)

25

Functions in Julia support optional positional arguments, as well as keyword arguments. The positional arguments are **always** given by their order, while they keyword arguments are **always** given by their keyword. Keywords are defined by using `;`. Example:

In [33]:
function g(x, y = 5; z = 2)
    x*z*y 
end

g (generic function with 2 methods)

In [34]:
g(5) # give x. default y, z

50

In [35]:
g(5, 3) # give x, y. default z

30

In [36]:
g(5; z = 3) # give x, z. default y

75

In [37]:
g(2, 4; z = 1.5) # give everything

12.0

### Duck-typing
Julia supports the "duck typing" approach. Simply put, functions work on whatever imput makes sense given their operations. This can be restricted if need be. 

In our example with `g`, anything that supports the function `*` will work.

In [38]:
A = rand(3, 3)
A

3×3 Array{Float64,2}:
 0.245923  0.759138   0.388055
 0.912909  0.0714382  0.377943
 0.60263   0.760084   0.648244

In [39]:
g(A)

3×3 Array{Float64,2}:
 2.45923  7.59138   3.88055
 9.12909  0.714382  3.77943
 6.0263   7.60084   6.48244

In [40]:
g(A, A; z = A)

3×3 Array{Float64,2}:
 1.11402  1.26964   0.996598
 1.40424  0.939244  0.979202
 1.78746  1.72308   1.46823 

In [41]:
g("string", "string"; z = "string") # * is string concatenation

"stringstringstring"

In [42]:
g("string", 5)

MethodError: MethodError: no method matching *(::String, ::Int64)
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502
  *(!Matched::Complex{Bool}, ::Real) at complex.jl:300
  *(!Matched::Missing, ::Number) at missing.jl:97
  ...

Now we got an error because the operation `String*Number` is not supported by default in Julia.

### Mutating vs. non-mutating functions

Mutable entities in Julia are passed by reference if possible. **By convention**, functions followed by `!` alter their contents and functions lacking `!` do not.

For example, let's look at the difference between `sort` and `sort!`.

In [43]:
v = [3, 5, 2]

3-element Array{Int64,1}:
 3
 5
 2

In [44]:
sort(v)

3-element Array{Int64,1}:
 2
 3
 5

In [45]:
v

3-element Array{Int64,1}:
 3
 5
 2

`sort(v)` returns a sorted array that contains the same elements as `v`, but `v` is left unchanged. <br><br>

On the other hand, when we run `sort!(v)`, the contents of v are sorted within the array `v`.

In [46]:
sort!(v)

3-element Array{Int64,1}:
 2
 3
 5

In [47]:
v

3-element Array{Int64,1}:
 2
 3
 5

## 1.6. Broadcasting
Julia compiles efficient machine code that is typically fast. This means that you don't have to vectorize your code; standard `for` loops are fast (in fact *faster* than vectorized code).

However the need often arises to apply some operations across multiple arguments element-wise. This is called **broadcasting**.

In Julia broadcasting is possible for any function, basic or user-defined. It is done via the simple syntax of adding a dot `.` before the parenthesis in the function call: `g.(x)`. 

Let's recall the previously defined `g`, now without keywords (broadcasting does not work on keywords)

In [48]:
function h(x, y = 5, z = 2)
    x*y*z 
end

h (generic function with 3 methods)

Let's now apply it to a vector `x`

In [49]:
x = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [50]:
h.(x)

3-element Array{Int64,1}:
 10
 20
 30

Let's now use vectors for both `y` and `z`:

In [51]:
y, z = rand(3), rand(3)

([0.613534, 0.163287, 0.240121], [0.604849, 0.0961783, 0.408509])

In [52]:
h.(x, y, z)

3-element Array{Float64,1}:
 0.3710952339555111 
 0.03140933908065123
 0.2942739152899318 

Same works even with matrices, or any other iterable. Julia will try to automatically deduce what is broadcastable and what should be the size of the output. E.g.:

In [53]:
x = fill(3, (3,3))

3×3 Array{Int64,2}:
 3  3  3
 3  3  3
 3  3  3

In [54]:
y, z = ones(3), fill(2, 3)

([1.0, 1.0, 1.0], [2, 2, 2])

In [55]:
h.(x, y, z)

3×3 Array{Float64,2}:
 6.0  6.0  6.0
 6.0  6.0  6.0
 6.0  6.0  6.0

## 1.7. Ranges
Ranges are useful shorthand notations that define a vector. This is done with two ways. One uses the syntax:
```
start:step:end
```
while the other
```
range(start, end; length = ...)
```

To make an exponential range one should use broadcast. Example:

In [56]:
r = 0:0.01:5

0.0:0.01:5.0

In [57]:
expr = 10 .^ r

501-element Array{Float64,1}:
      1.0               
      1.023292992280754 
      1.0471285480508996
      1.0715193052376064
      1.096478196143185 
      1.1220184543019633
      1.1481536214968828
      1.1748975549395295
      1.202264434617413 
      1.2302687708123816
      1.2589254117941673
      1.288249551693134 
      1.318256738556407 
      ⋮                 
  77624.71166286911     
  79432.82347242822     
  81283.05161640995     
  83176.37711026709     
  85113.80382023759     
  87096.35899560814     
  89125.0938133746      
  91201.08393559097     
  93325.43007969906     
  95499.25860214369     
  97723.72209558112     
 100000.0               

# 2. Linear algebra in Julia

## 2.1. Basic linalg operations

First let's define a random matrix

In [73]:
A = rand(1:10, (3,3)) # this will take random numbers from 1:10

3×3 Array{Int64,2}:
 5  6  5
 8  3  8
 3  2  4

and a vector of ones

In [59]:
x = fill(1.0, (3))

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

Notice the dimensionality difference between `A` and `x`! Julia defines the aliases `Vector{Type}=Array{Type,1}` and `Matrix{Type}=Array{Type,2}`. 

Many of the basic operations are the same as in other languages:
#### Multiplication

In [60]:
b = A*x

3-element Array{Float64,1}:
 8.0
 5.0
 5.0

#### Transposition
As in other languages `A'` is the conjugate transpose

In [61]:
A'

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 3  2  2
 3  1  1
 2  2  2

#### Transposed multiplication
Julia allows us to write this without *

In [63]:
A'A

3×3 Array{Int64,2}:
 17  13  14
 13  11  10
 14  10  12

#### Solving linear systems 
The problem $Ax=b$ for ***square*** $A$ is solved by the \ function.

In [74]:
A\b

3-element Array{Float64,1}:
 -1.9090909090909096
  1.1818181818181817
  2.0909090909090917

## 2.2. Special matrix structures

Matrix structure is very important in linear algebra. To see *how* important it is, let's work with a larger linear system. Use the `LinearAlgebra` standard package to get access to structured matrices:

In [65]:
using LinearAlgebra

In [66]:
n = 1000
A = randn(n,n); # a nxn matrix with normally distributed numbers

Julia can often infer special matrix structure

In [67]:
Asym = A + A'
issymmetric(Asym)

true

but sometimes floating point error might get in the way.

In [68]:
Asym_noisy = copy(Asym)
Asym_noisy[1,2] += 5eps()

-1.9275615587017396

In [69]:
issymmetric(Asym_noisy)

false

Luckily we can declare structure explicitly with, for example, `Diagonal`, `Triangular`, `Symmetric`, `Hermitian`, `Tridiagonal` and `SymTridiagonal`.

In [76]:
Asym_explicit = Symmetric(Asym_noisy);

Using explicit structures (e.g. `Triangular` can have both performance advantages in specific algorithms, but also allow to use algorithms that only exist given a specific structure!

#### performance benefit
Using the `Tridiagonal` and `SymTridiagonal` types to store tridiagonal matrices makes it possible to work with potentially very large tridiagonal problems. The following problem would not be possible to solve on a laptop if the matrix had to be stored as a (dense) `Matrix` type.

In [71]:
n = 1_000_000;
A = SymTridiagonal(randn(n), randn(n-1));
@time eigmax(A)

  1.119838 seconds (651.49 k allocations: 215.138 MiB, 13.08% gc time)


6.330170220666282

# 3. Exercises

## 3.1. Counting nucleotides
Use the help functionality of Julia (typing `?` before any function name) and learn about the functions `count`, `occursin` and `error`. Then, create a function that given a DNA strand (as a `String`) it counts how much of each nucleotide is present. The function should throw an error if an invalid nucleotide is encountered.

## 3.2. Collatz conjecture
Given a positive integer, create a function that counts the steps it takes to reach `1` following the [Collatz conjecture algorithm](https://en.wikipedia.org/wiki/Collatz_conjecture).

## 3.3. Fibonacci numbers
Using recursion create a function that given `n` it returns the `n`-th Fibonacci number.

## 3.4 Binomial sampling
A random variable X~Bin(n,p) is defined the number of successes in n trials where each trial has a success probability p. For example, if Bin(10,0.5), then X is the number of coin flips that turn up heads in 10 flips.

Using only `rand()` (uniform random numbers), write a function `binomial_rv(n,p)` that produces one draw of `Bin(n,p)`.

## 3.5. Logistic map
Create a function that given `r1, r2` (and other optional keywords), it plots the orbit diagram of the logistic map $x_{n+1} = rx(1-x)$ from `r1` to `r2`. If you are already familiar with `matplotlib`, you should use `PyPlot.scatter` for plotting and you will probably need the function `fill`.